version: "3.8"

services:
  # MySQL database service
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - node-onboarder

  # Node.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./:/app
    networks:
      - node-onboarder
    depends_on:
      - mysql  

  # Nginx reverse proxy service
  nginx:
    image: nginx:latest
    container_name: node-onboarder-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./node_onboarder.conf:/etc/nginx/conf.d/node_onboarder.conf:ro
    depends_on:
      - app  
    networks:
      - node-onboarder

networks:
  node-onboarder:
    driver: bridge