version: '3.8'

services:
  db:
    image: mysql:8.3
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3600:3500"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "3700:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
